_target_: src.models.sir_module.NISpLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.nis_net.NISPNet
  input_size: 4 
  latent_size: 2 
  output_size: 4 
  hidden_units: 64 
  hidden_units_dyn: 64
  is_normalized: true

# compile model for faster training with pytorch 2.0
compile: false
lambdas: 1
trainset_fp: ${data.path.train}
