_target_: src.models.sir_module.NISLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.nis_net.NISNet
  input_size: 2 
  latent_size: 1 
  output_size: 2 
  hidden_units: 64 
  is_normalized: true

# compile model for faster training with pytorch 2.0
compile: false
